name: Swift-Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
    - uses: actions/checkout@v2
    - name: Xcode select
      run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
    - name: Build and Test
      run: |
        swift test
