name: Swift-Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        xcode: [12.4, 13.2.1]
        exclude:
          - os: macos-10.15
            xcode: 13.2.1
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: swift test
