name: Xcode-Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        xcode: [12.4, 13.2.1]
        exclude:
          - os: macos-10.15
            xcode: 13.2.1
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild build-for-testing test-without-building \
          -workspace "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          ENABLE_TESTABILITY=YES | xcpretty -c;
      env:
        PROJECT: LoginServiceKit.xcworkspace
        SCHEME: LoginServiceKit
        SDK: macosx
        DESTINATION: arch=x86_64
